### ISSUE TITLE
Create a sidebar with github, linkedIn and Gmail Icons

### ISSUE THREAD

**Issue by siva9495** [siva9495/sivaprasad#4]
![Screenshot (16)](https://github.com/siva9495/Siva-Portfolio/assets/57442699/19801bb7-e609-4995-8fb1-9782c560becf)

**Comment by ghost** [comment]
Hey, I'd like to try this one :)

**Comment by siva9495** [comment]
> Hey, I'd like to try this one :)

sorry, I am doing it myself
